const cfg = window.FAIRSHARE_CONFIG || {};
const configured = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_URL.startsWith('YOUR_');
const sb = configured ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;

const state = { user:null, profile:null, friends:[], requests:[], groups:[], activeGroup:null, members:[], expenses:[], settlements:[] };
const $ = id => document.getElementById(id);
const rp = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function initials(name){return (name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'?'}
function avatar(name){return `<div class="avatar">${esc(initials(name))}</div>`}
function fmtDate(v){return new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(v))}
function modal(html){$('modalContent').innerHTML=html;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
window.closeModal=closeModal;
$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};

function authTab(which){document.querySelectorAll('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authTab===which));$('loginForm').classList.toggle('hidden',which!=='login');$('signupForm').classList.toggle('hidden',which!=='signup')}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>authTab(b.dataset.authTab));

async function init(){
  if(!configured){
    $('authView').innerHTML=`<div class="auth-card"><div class="brand brand-center"><div class="mark">F</div><div><strong>FairShare setup</strong><span>Connect Supabase first</span></div></div><div class="notice">Open <b>config.js</b> and replace the two placeholders with your Supabase Project URL and anon public key. Then run <b>supabase-schema.sql</b> once in Supabase SQL Editor.</div><p class="auth-note">The included README.md has exact steps.</p></div>`;
    return;
  }
  const {data:{session}}=await sb.auth.getSession();
  if(session) await enterApp(session.user); else showAuth();
  sb.auth.onAuthStateChange(async (_event,session)=>{if(session?.user)await enterApp(session.user);else showAuth()});
}
function showAuth(){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}
async function enterApp(user){state.user=user;await loadProfile();$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('sideName').textContent=state.profile.display_name;$('sideEmail').textContent=user.email;$('sideAvatar').textContent=initials(state.profile.display_name);await Promise.all([loadFriends(),loadGroups()]);renderDashboard();}

$('loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)toast(error.message)};
$('signupForm').onsubmit=async e=>{e.preventDefault();const name=$('signupName').value.trim();const {error}=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{display_name:name}}});if(error)toast(error.message);else toast('Account created. Check your email if confirmation is enabled.')};
$('logoutBtn').onclick=()=>sb.auth.signOut();

async function loadProfile(){
  let {data,error}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();
  if(error) throw error;
  if(!data){const name=state.user.user_metadata?.display_name||state.user.email.split('@')[0];const r=await sb.from('profiles').upsert({id:state.user.id,display_name:name,email:state.user.email}).select().single();if(r.error)throw r.error;data=r.data}
  state.profile=data;
}
async function loadFriends(){
  const [{data:friends,error:e1},{data:req,error:e2}]=await Promise.all([
    sb.rpc('get_my_friends'),
    sb.from('friend_requests').select('id,status,created_at,sender_id,receiver_id,sender:profiles!friend_requests_sender_id_fkey(id,display_name,email),receiver:profiles!friend_requests_receiver_id_fkey(id,display_name,email)').or(`sender_id.eq.${state.user.id},receiver_id.eq.${state.user.id}`).eq('status','pending')
  ]);
  if(e1)throw e1;if(e2)throw e2;state.friends=friends||[];state.requests=req||[];
}
async function loadGroups(){const {data,error}=await sb.rpc('get_my_groups');if(error)throw error;state.groups=data||[]}

function setTab(tab,title,sub){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(tab).classList.remove('hidden');$('pageTitle').textContent=title;$('pageSub').textContent=sub;$('topActions').innerHTML=''}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{if(b.dataset.tab==='dashboard')renderDashboard();if(b.dataset.tab==='friends'){await loadFriends();renderFriends()}if(b.dataset.tab==='groups'){await loadGroups();renderGroups()}});

function renderDashboard(){setTab('dashboard','Dashboard','Your shared expenses at a glance.');const totalGroups=state.groups.length,friendCount=state.friends.length;$('dashboard').innerHTML=`<div class="summary"><div class="card"><span class="muted">Groups</span><strong>${totalGroups}</strong><span class="muted">Active shared ledgers</span></div><div class="card"><span class="muted">Friends</span><strong>${friendCount}</strong><span class="muted">Accepted connections</span></div><div class="card"><span class="muted">Account</span><strong>${esc(state.profile.display_name)}</strong><span class="muted">${esc(state.user.email)}</span></div></div><div class="panel"><div class="head"><div><h2>Your groups</h2><p>Open a group to add expenses and settle balances.</p></div><button class="primary" onclick="showCreateGroup()">+ New group</button></div>${groupCards(state.groups.slice(0,6))}</div>`}
function groupCards(groups){if(!groups.length)return '<div class="empty">No groups yet. Create one and add your friends.</div>';return `<div class="groups-grid">${groups.map(g=>`<article class="group-card" onclick="openGroup('${g.id}')"><span class="pill">${g.member_count} member${g.member_count==1?'':'s'}</span><h3>${esc(g.name)}</h3><p>${esc(g.description||'Shared expenses')}</p></article>`).join('')}</div>`}

function renderFriends(){setTab('friends','Friends','Add people by email, then include them in groups.');$('topActions').innerHTML='<button class="primary" onclick="showAddFriend()">+ Add friend</button>';const incoming=state.requests.filter(r=>r.receiver_id===state.user.id);const outgoing=state.requests.filter(r=>r.sender_id===state.user.id);$('friends').innerHTML=`${incoming.length?`<div class="panel" style="margin-bottom:18px"><div class="head"><div><h2>Friend requests</h2><p>Requests waiting for you.</p></div></div>${incoming.map(r=>`<div class="row">${avatar(r.sender.display_name)}<div class="grow"><strong>${esc(r.sender.display_name)}</strong><span>${esc(r.sender.email)}</span></div><button class="small-btn" onclick="respondFriend('${r.id}','accepted')">Accept</button><button class="small-btn" onclick="respondFriend('${r.id}','declined')">Decline</button></div>`).join('')}</div>`:''}<div class="grid"><div class="panel"><div class="head"><div><h2>Your friends</h2><p>${state.friends.length} connection${state.friends.length===1?'':'s'}</p></div></div>${state.friends.length?state.friends.map(f=>`<div class="row">${avatar(f.display_name)}<div class="grow"><strong>${esc(f.display_name)}</strong><span>${esc(f.email)}</span></div></div>`).join(''):'<div class="empty">No friends yet.</div>'}</div><div class="panel"><div class="head"><div><h2>Sent requests</h2><p>Pending invitations</p></div></div>${outgoing.length?outgoing.map(r=>`<div class="row">${avatar(r.receiver.display_name)}<div class="grow"><strong>${esc(r.receiver.display_name)}</strong><span>${esc(r.receiver.email)}</span></div><span class="pill">Pending</span></div>`).join(''):'<div class="empty">No pending requests.</div>'}</div></div>`}
window.showAddFriend=()=>modal(`<div class="modalhead"><h2>Add friend</h2><button class="close" onclick="closeModal()">×</button></div><form id="friendForm" class="form-grid"><label class="field">Friend's exact email<input id="friendEmail" type="email" required placeholder="friend@example.com"></label><button class="primary wide">Send friend request</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id==='friendForm'){e.preventDefault();const {data,error}=await sb.rpc('send_friend_request',{target_email:$('friendEmail').value.trim().toLowerCase()});if(error)toast(error.message);else{toast(data||'Friend request sent');closeModal();await loadFriends();renderFriends()}}});
window.respondFriend=async(id,status)=>{const {error}=await sb.from('friend_requests').update({status,responded_at:new Date().toISOString()}).eq('id',id).eq('receiver_id',state.user.id);if(error)toast(error.message);else{await loadFriends();renderFriends();toast(status==='accepted'?'Friend added':'Request declined')}};

function renderGroups(){setTab('groups','Groups','Create a group and add accepted friends.');$('topActions').innerHTML='<button class="primary" onclick="showCreateGroup()">+ New group</button>';$('groups').innerHTML=groupCards(state.groups)}
window.showCreateGroup=()=>modal(`<div class="modalhead"><h2>Create group</h2><button class="close" onclick="closeModal()">×</button></div><form id="groupForm" class="form-grid"><label class="field">Group name<input id="groupName" required placeholder="e.g. Japan Trip"></label><label class="field">Description<input id="groupDesc" placeholder="Optional"></label>${state.friends.length?`<div><strong style="font-size:13px">Add friends</strong><div class="checks" style="margin-top:8px">${state.friends.map(f=>`<label class="check"><input type="checkbox" name="friend" value="${f.id}">${avatar(f.display_name)}<span>${esc(f.display_name)}<small class="muted">${esc(f.email)}</small></span></label>`).join('')}</div></div>`:'<div class="notice">You have no friends yet. The group will start with just you; friends can be added later.</div>'}<button class="primary wide">Create group</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id==='groupForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=friend]:checked')].map(x=>x.value);const {data,error}=await sb.rpc('create_group_with_members',{group_name:$('groupName').value.trim(),group_description:$('groupDesc').value.trim(),member_ids:ids});if(error)toast(error.message);else{closeModal();await loadGroups();toast('Group created');openGroup(data)}}});

window.openGroup=async id=>{
  const group=state.groups.find(g=>g.id===id)||{id,name:'Group'};state.activeGroup=group;
  const [{data:members,error:e1},{data:expenses,error:e2},{data:settlements,error:e3}]=await Promise.all([
    sb.from('group_members').select('user_id,profiles(id,display_name,email)').eq('group_id',id),
    sb.from('expenses').select('id,description,amount,currency,paid_by,created_at,payer:profiles!expenses_paid_by_fkey(id,display_name),expense_splits(user_id,amount,profile:profiles(id,display_name,email))').eq('group_id',id).order('created_at',{ascending:false}),
    sb.from('settlements').select('id,from_user,to_user,amount,created_at,from_profile:profiles!settlements_from_user_fkey(id,display_name),to_profile:profiles!settlements_to_user_fkey(id,display_name)').eq('group_id',id).order('created_at',{ascending:false})
  ]);if(e1)throw e1;if(e2)throw e2;if(e3)throw e3;state.members=(members||[]).map(m=>m.profiles);state.expenses=expenses||[];state.settlements=settlements||[];renderGroup();
}
function calculateBalances(){const b=Object.fromEntries(state.members.map(m=>[m.id,0]));for(const e of state.expenses){b[e.paid_by]=(b[e.paid_by]||0)+Number(e.amount);for(const s of e.expense_splits)b[s.user_id]=(b[s.user_id]||0)-Number(s.amount)}for(const s of state.settlements){b[s.from_user]=(b[s.from_user]||0)+Number(s.amount);b[s.to_user]=(b[s.to_user]||0)-Number(s.amount)}return b}
function simplifyDebts(){const b=calculateBalances(),credit=[],debt=[],out=[];Object.entries(b).forEach(([id,v])=>{if(v>0.005)credit.push({id,amount:v});if(v<-0.005)debt.push({id,amount:-v})});let i=0,j=0;while(i<debt.length&&j<credit.length){const x=Math.min(debt[i].amount,credit[j].amount);out.push({from:debt[i].id,to:credit[j].id,amount:x});debt[i].amount-=x;credit[j].amount-=x;if(debt[i].amount<.005)i++;if(credit[j].amount<.005)j++}return out}
function memberName(id){return state.members.find(m=>m.id===id)?.display_name||'Unknown'}
function renderGroup(){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('groupDetail').classList.remove('hidden');$('pageTitle').textContent=state.activeGroup.name;$('pageSub').textContent=state.activeGroup.description||`${state.members.length} members`;$('topActions').innerHTML='<button class="secondary" onclick="showAddMembers()">+ Member</button> <button class="primary" onclick="showAddExpense()">+ Expense</button>';const b=calculateBalances(),d=simplifyDebts(),mine=b[state.user.id]||0,total=state.expenses.reduce((x,e)=>x+Number(e.amount),0);$('groupDetail').innerHTML=`<button class="back" onclick="renderGroups()">← All groups</button><div class="summary" style="margin-top:16px"><div class="card"><span class="muted">Your balance</span><strong class="${mine>=0?'positive':'negative'}">${mine>=0?'You are owed '+rp(mine):'You owe '+rp(-mine)}</strong><span class="muted">After recorded settlements</span></div><div class="card"><span class="muted">Group spend</span><strong>${rp(total)}</strong><span class="muted">${state.expenses.length} expense${state.expenses.length===1?'':'s'}</span></div><div class="card"><span class="muted">Members</span><div class="member-stack">${state.members.slice(0,6).map(m=>avatar(m.display_name)).join('')}</div><span class="muted">${state.members.length} people</span></div></div><div class="grid"><div class="panel"><div class="head"><div><h2>Expenses</h2><p>Newest first</p></div></div>${state.expenses.length?state.expenses.map(e=>`<div class="row"><div class="icon">$</div><div class="grow"><strong>${esc(e.description)}</strong><span>${fmtDate(e.created_at)} · paid by ${esc(e.payer.display_name)}</span></div><div class="amt"><strong>${rp(e.amount)}</strong><span>${e.expense_splits.length} people</span></div></div>`).join(''):'<div class="empty">No expenses yet.</div>'}</div><div class="panel"><div class="head"><div><h2>Settle up</h2><p>Minimum suggested transfers</p></div></div>${d.length?d.map(x=>`<div class="row">${avatar(memberName(x.from))}<div class="grow"><strong>${esc(memberName(x.from))} → ${esc(memberName(x.to))}</strong><span>Suggested settlement</span></div><strong>${rp(x.amount)}</strong>${x.from===state.user.id?`<button class="small-btn" onclick="recordSettlement('${x.from}','${x.to}',${x.amount})">Paid</button>`:''}</div>`).join(''):'<div class="empty">All settled!</div>'}</div></div>`}

window.showAddMembers=()=>{const existing=new Set(state.members.map(m=>m.id)),eligible=state.friends.filter(f=>!existing.has(f.id));modal(`<div class="modalhead"><h2>Add group members</h2><button class="close" onclick="closeModal()">×</button></div>${eligible.length?`<form id="addMembersForm" class="form-grid"><div class="checks">${eligible.map(f=>`<label class="check"><input type="checkbox" name="member" value="${f.id}">${avatar(f.display_name)}<span>${esc(f.display_name)}<small class="muted">${esc(f.email)}</small></span></label>`).join('')}</div><button class="primary wide">Add selected</button></form>`:'<div class="empty">All of your friends are already in this group.</div>'}`)};
document.addEventListener('submit',async e=>{if(e.target.id==='addMembersForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=member]:checked')].map(x=>x.value);const {error}=await sb.rpc('add_group_members',{target_group_id:state.activeGroup.id,member_ids:ids});if(error)toast(error.message);else{closeModal();await openGroup(state.activeGroup.id);toast('Members added')}}});

window.showAddExpense=()=>modal(`<div class="modalhead"><h2>Add expense</h2><button class="close" onclick="closeModal()">×</button></div><form id="expenseForm" class="form-grid"><label class="field">Description<input id="expenseDesc" required placeholder="e.g. Dinner"></label><label class="field">Amount (IDR)<input id="expenseAmount" type="number" min="1" step="1" required placeholder="0"></label><label class="field">Paid by<select id="expensePayer">${state.members.map(m=>`<option value="${m.id}" ${m.id===state.user.id?'selected':''}>${esc(m.display_name)}</option>`).join('')}</select></label><div><strong style="font-size:13px">Split equally between</strong><div class="checks" style="margin-top:8px">${state.members.map(m=>`<label class="check"><input type="checkbox" name="split" value="${m.id}" checked>${avatar(m.display_name)}<span>${esc(m.display_name)}</span></label>`).join('')}</div></div><button class="primary wide">Save expense</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id==='expenseForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=split]:checked')].map(x=>x.value),amount=Number($('expenseAmount').value);if(!ids.length)return toast('Select at least one person');const {data,error}=await sb.rpc('create_equal_expense',{target_group_id:state.activeGroup.id,expense_description:$('expenseDesc').value.trim(),expense_amount:amount,payer_id:$('expensePayer').value,participant_ids:ids});if(error)toast(error.message);else{closeModal();await openGroup(state.activeGroup.id);toast('Expense added')}}});

window.recordSettlement=async(from,to,amount)=>{if(!confirm(`Record ${rp(amount)} as paid from ${memberName(from)} to ${memberName(to)}?`))return;const {error}=await sb.from('settlements').insert({group_id:state.activeGroup.id,from_user:from,to_user:to,amount:Math.round(amount*100)/100});if(error)toast(error.message);else{await openGroup(state.activeGroup.id);toast('Settlement recorded')}};

init().catch(err=>{console.error(err);toast(err.message||'Something went wrong')});
