const cfg = window.FAIRSHARE_CONFIG || {};
const configured = cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_URL.startsWith('YOUR_');
const sb = configured ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;

const state = { user:null, profile:null, friends:[], requests:[], groups:[], activeGroup:null, members:[], expenses:[], settlements:[] };
const $ = id => document.getElementById(id);
const CURRENCIES = ['IDR','USD','SGD','EUR','GBP','JPY','AUD','MYR','CNY','THB'];
const CURRENCY_LOCALE = {IDR:'id-ID',USD:'en-US',SGD:'en-SG',EUR:'de-DE',GBP:'en-GB',JPY:'ja-JP',AUD:'en-AU',MYR:'ms-MY',CNY:'zh-CN',THB:'th-TH'};
const AVATARS = ['💸','💰','🧾','🐼','🐯','🦊','🐸','🐧','🚀','🌊','⭐','🪙','😎','🤓','🥳','🧠','🦁','🐨','🐙','🦄','🍜','☕','✈️','🎮'];
const GROUP_ICONS = ['🍜','☕','✈️','🏠','🏖️','🎉','🎓','💼','🎮','🎬','🍻','🍕','🚗','🛒','🏕️','⚽','🎵','💳','🧳','🎁','🏃','🐾','🌴','⭐'];
const money = (n,currency='IDR') => new Intl.NumberFormat(CURRENCY_LOCALE[currency]||'en-US',{style:'currency',currency,maximumFractionDigits:['IDR','JPY'].includes(currency)?0:2}).format(Number(n)||0);
const rp = n => money(n,'IDR');
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sleep = ms => new Promise(r=>setTimeout(r,ms));
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function initials(name){return (name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'?'}
function avatar(name,key=''){const content=AVATARS.includes(key)?key:esc(initials(name));return `<div class="avatar ${AVATARS.includes(key)?'emoji-avatar':''}">${content}</div>`}
function memberAvatar(id){const m=state.members.find(x=>x.id===id);return avatar(m?.display_name||'?',m?.avatar_key||'')}
function groupIcon(group,size=''){const key=group?.icon_key||'';const content=GROUP_ICONS.includes(key)?key:esc(initials(group?.name||'Group'));return `<div class="group-icon ${GROUP_ICONS.includes(key)?'emoji-group-icon':''} ${size}">${content}</div>`}
function fmtDate(v){if(!v)return '';const d=/^\d{4}-\d{2}-\d{2}$/.test(String(v))?new Date(`${v}T12:00:00`):new Date(v);return new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(d)}
function fmtDateTime(v){return new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
function todayISO(){const d=new Date();const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function currencyOptions(selected='IDR'){return CURRENCIES.map(c=>`<option value="${c}" ${c===selected?'selected':''}>${c}</option>`).join('')}
function parseMoneyInput(value){let v=String(value||'').trim().replace(/\s/g,'');if(!v)return 0;const hasComma=v.includes(','),hasDot=v.includes('.');if(hasComma&&hasDot){const decimal=v.lastIndexOf(',')>v.lastIndexOf('.')?',':'.';v=decimal===','?v.replace(/\./g,'').replace(',','.'):v.replace(/,/g,'')}else if(hasComma){const tail=v.split(',').pop();v=(tail.length<=2)?v.replace(/\./g,'').replace(',','.'):v.replace(/,/g,'')}else if(hasDot){const tail=v.split('.').pop();if(tail.length===3 && v.split('.').length>1)v=v.replace(/\./g,'')}return Number(v.replace(/[^0-9.-]/g,''))||0}
function bindMoneyField(inputId,currencyId,previewId){const input=$(inputId),curr=$(currencyId),preview=$(previewId);if(!input||!curr||!preview)return;const update=()=>{const n=parseMoneyInput(input.value);preview.textContent=n?money(n,curr.value):money(0,curr.value)};input.addEventListener('input',update);curr.addEventListener('change',update);input.addEventListener('blur',()=>{const n=parseMoneyInput(input.value);if(!n)return;input.value=new Intl.NumberFormat(CURRENCY_LOCALE[curr.value]||'en-US',{maximumFractionDigits:['IDR','JPY'].includes(curr.value)?0:2}).format(n);update()});input.addEventListener('focus',()=>{const n=parseMoneyInput(input.value);if(n)input.value=String(n)});update()}
function moneyLines(map,cls=''){const entries=Object.entries(map||{}).filter(([,v])=>Math.abs(Number(v))>0.005);if(!entries.length)return `<strong class="${cls}">${money(0,'IDR')}</strong>`;return `<div class="metric-money-lines">${entries.map(([c,v])=>{const n=Number(v),effective=cls||(n>0?'positive':n<0?'negative':''),prefix=n<0?'-':(cls==='positive'?'+':cls==='negative'?'-':n>0?'+':'');return `<strong class="${effective}">${prefix}${money(Math.abs(n),c)}</strong>`}).join('')}</div>`}
function modal(html){$('modalContent').innerHTML=html;$('modal').classList.add('show');document.body.classList.add('modal-open');requestAnimationFrame(()=>$('modalContent').classList.add('modal-enter'))}
function closeModal(){$('modalContent').classList.remove('modal-enter');$('modal').classList.remove('show');document.body.classList.remove('modal-open')}
window.closeModal=closeModal;
$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};

function authTab(which){document.querySelectorAll('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authTab===which));$('loginForm').classList.toggle('hidden',which!=='login');$('signupForm').classList.toggle('hidden',which!=='signup')}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>authTab(b.dataset.authTab));

async function init(){
  if(!configured){
    $('authView').innerHTML=`<div class="auth-card pop"><div class="brand brand-center"><div class="mark">R</div><div><strong>Rekapuang setup</strong><span>Connect Supabase first</span></div></div><div class="notice">Open <b>config.js</b> and replace the two placeholders with your Supabase Project URL and anon public key. Then run <b>supabase-schema.sql</b> once in Supabase SQL Editor.</div><p class="auth-note">The included README.md has exact steps.</p></div>`;
    return;
  }
  const {data:{session}}=await sb.auth.getSession();
  if(session) await enterApp(session.user); else showAuth();
  sb.auth.onAuthStateChange(async (_event,session)=>{if(session?.user)await enterApp(session.user);else showAuth()});
}
function showAuth(){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}
async function enterApp(user){state.user=user;await loadProfile();$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('sideName').textContent=state.profile.display_name;$('sideEmail').textContent=user.email;renderSideAvatar();await Promise.all([loadFriends(),loadGroups()]);renderDashboard();}

$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Logging in...';const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error){toast(error.message);btn.disabled=false;btn.textContent='Log in'}};
$('signupForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Creating...';const name=$('signupName').value.trim();const {error}=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{display_name:name}}});if(error)toast(error.message);else toast('Account created. Check your email if confirmation is enabled.');btn.disabled=false;btn.textContent='Create account'};
$('logoutBtn').onclick=()=>sb.auth.signOut();

async function loadProfile(){
  let {data,error}=await sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle();
  if(error) throw error;
  if(!data){const name=state.user.user_metadata?.display_name||state.user.email.split('@')[0];const r=await sb.from('profiles').upsert({id:state.user.id,display_name:name,email:state.user.email}).select().single();if(r.error)throw r.error;data=r.data}
  state.profile=data;
}
async function loadFriends(){
  const [{data:friends,error:e1},{data:req,error:e2}]=await Promise.all([
    sb.rpc('get_my_friends'),
    sb.from('friend_requests').select('id,status,created_at,sender_id,receiver_id,sender:profiles!friend_requests_sender_id_fkey(id,display_name,email,avatar_key),receiver:profiles!friend_requests_receiver_id_fkey(id,display_name,email,avatar_key)').or(`sender_id.eq.${state.user.id},receiver_id.eq.${state.user.id}`).eq('status','pending')
  ]);
  if(e1)throw e1;if(e2)throw e2;
  state.friends=friends||[];state.requests=req||[];
  const ids=state.friends.map(f=>f.id);
  if(ids.length){const {data:profiles}=await sb.from('profiles').select('id,avatar_key').in('id',ids);const byId=Object.fromEntries((profiles||[]).map(p=>[p.id,p.avatar_key]));state.friends=state.friends.map(f=>({...f,avatar_key:byId[f.id]||''}))}
}
async function loadGroups(){const {data,error}=await sb.rpc('get_my_groups_v2');if(error)throw error;state.groups=data||[]}

function setTab(tab,title,sub){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(tab).classList.remove('hidden');$('pageTitle').textContent=title;$('pageSub').textContent=sub;$('topActions').innerHTML=''}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{if(b.dataset.tab==='dashboard')renderDashboard();if(b.dataset.tab==='friends'){await loadFriends();renderFriends()}if(b.dataset.tab==='groups'){await loadGroups();renderGroups()}});

function renderDashboard(){setTab('dashboard','Dashboard','Everything shared, clear at a glance.');const totalGroups=state.groups.length,friendCount=state.friends.length;$('dashboard').innerHTML=`<div class="hero-card pop"><div><span class="eyebrow">WELCOME BACK</span><h2>Hi, ${esc(state.profile.display_name)} 👋</h2><p>Keep expenses and repayments in one place, so nobody has to remember who paid what.</p></div><button class="primary" onclick="showCreateGroup()">+ New group</button></div><div class="summary stagger"><div class="card metric"><div class="metric-icon">◎</div><span class="muted">Groups</span><strong>${totalGroups}</strong><span class="muted">Active shared ledgers</span></div><div class="card metric"><div class="metric-icon">↔</div><span class="muted">Friends</span><strong>${friendCount}</strong><span class="muted">Accepted connections</span></div><button class="card metric account-card" onclick="showAvatarPicker()"><div class="account-avatar-wrap">${avatar(state.profile.display_name,state.profile.avatar_key)}</div><span class="muted">Account · change icon</span><strong class="name-metric">${esc(state.profile.display_name)}</strong><span class="muted account-email">${esc(state.user.email)}</span></button></div><div class="panel lift"><div class="head"><div><h2>Your groups</h2><p>Open a group to track expenses and repayments.</p></div></div>${groupCards(state.groups.slice(0,6))}</div>`}
function groupCards(groups){if(!groups.length)return '<div class="empty">No groups yet. Create one and add your friends.</div>';return `<div class="groups-grid">${groups.map((g,i)=>`<article class="group-card pop ${g.status==='closed'?'closed-group':''}" style="animation-delay:${i*45}ms" onclick="openGroup('${g.id}')">${groupIcon(g)}<span class="pill ${g.status==='closed'?'pill-closed':''}">${g.status==='closed'?'Closed':`${g.member_count} member${g.member_count==1?'':'s'}`}</span><h3>${esc(g.name)}</h3><p>${esc(g.description||'Shared expenses')}</p><div class="card-arrow">→</div></article>`).join('')}</div>`}

function renderFriends(){setTab('friends','Friends','Add people by email, then include them in groups.');$('topActions').innerHTML='<button class="primary" onclick="showAddFriend()">+ Add friend</button>';const incoming=state.requests.filter(r=>r.receiver_id===state.user.id);const outgoing=state.requests.filter(r=>r.sender_id===state.user.id);$('friends').innerHTML=`${incoming.length?`<div class="panel lift" style="margin-bottom:18px"><div class="head"><div><h2>Friend requests</h2><p>Requests waiting for you.</p></div></div>${incoming.map(r=>`<div class="row">${avatar(r.sender.display_name,r.sender.avatar_key)}<div class="grow"><strong>${esc(r.sender.display_name)}</strong><span>${esc(r.sender.email)}</span></div><button class="small-btn" onclick="respondFriend('${r.id}','accepted')">Accept</button><button class="small-btn" onclick="respondFriend('${r.id}','declined')">Decline</button></div>`).join('')}</div>`:''}<div class="grid"><div class="panel lift"><div class="head"><div><h2>Your friends</h2><p>${state.friends.length} connection${state.friends.length===1?'':'s'}</p></div></div>${state.friends.length?state.friends.map(f=>`<div class="row">${avatar(f.display_name,f.avatar_key)}<div class="grow"><strong>${esc(f.display_name)}</strong><span>${esc(f.email)}</span></div><button class="small-btn friend-remove" onclick="confirmRemoveFriend('${f.id}','${esc(f.display_name).replace(/'/g, '&#39;')}')">Remove</button></div>`).join(''):'<div class="empty">No friends yet.</div>'}</div><div class="panel lift"><div class="head"><div><h2>Sent requests</h2><p>Pending invitations</p></div></div>${outgoing.length?outgoing.map(r=>`<div class="row">${avatar(r.receiver.display_name,r.receiver.avatar_key)}<div class="grow"><strong>${esc(r.receiver.display_name)}</strong><span>${esc(r.receiver.email)}</span></div><span class="pill">Pending</span></div>`).join(''):'<div class="empty">No pending requests.</div>'}</div></div>`}
window.showAddFriend=()=>modal(`<div class="modalhead"><h2>Add friend</h2><button class="close" onclick="closeModal()">×</button></div><form id="friendForm" class="form-grid"><label class="field">Friend's exact email<input id="friendEmail" type="email" required placeholder="friend@example.com"></label><button class="primary wide">Send friend request</button></form>`);
window.confirmRemoveFriend=(friendId,friendName)=>modal(`<div class="modalhead"><div><h2>Remove friend?</h2><p class="modal-sub">This removes the friend connection between you and ${esc(friendName)}.</p></div><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="notice danger-notice"><strong>Existing group history will not be deleted.</strong> If you are already together in a group, that membership and its expenses/settlements stay intact.</div><button class="danger wide" onclick="removeFriend('${friendId}')">Remove friend</button><button class="secondary wide" onclick="closeModal()">Cancel</button></div>`);
window.removeFriend=async friendId=>{const {error}=await sb.rpc('remove_friend',{target_user_id:friendId});if(error)return toast(error.message);closeModal();await loadFriends();renderFriends();toast('Friend removed')};
document.addEventListener('submit',async e=>{if(e.target.id==='friendForm'){e.preventDefault();const {data,error}=await sb.rpc('send_friend_request',{target_email:$('friendEmail').value.trim().toLowerCase()});if(error)toast(error.message);else{toast(data||'Friend request sent');closeModal();await loadFriends();renderFriends()}}});
window.respondFriend=async(id,status)=>{const {error}=await sb.from('friend_requests').update({status,responded_at:new Date().toISOString()}).eq('id',id).eq('receiver_id',state.user.id);if(error)toast(error.message);else{await loadFriends();renderFriends();toast(status==='accepted'?'Friend added':'Request declined')}};

function renderGroups(){setTab('groups','Groups','Create a group and add accepted friends.');$('topActions').innerHTML='<button class="primary" onclick="showCreateGroup()">+ New group</button>';const active=state.groups.filter(g=>g.status!=='closed'),closed=state.groups.filter(g=>g.status==='closed');$('groups').innerHTML=`<div class="panel lift"><div class="head"><div><h2>Active groups</h2><p>${active.length} active shared ledger${active.length===1?'':'s'}</p></div></div>${groupCards(active)}</div>${closed.length?`<div class="panel lift" style="margin-top:18px"><div class="head"><div><h2>Closed groups</h2><p>Read-only history. You can still review expenses and settlements.</p></div></div>${groupCards(closed)}</div>`:''}`}
window.showCreateGroup=()=>modal(`<div class="modalhead"><div><h2>Create group</h2><p class="modal-sub">Pick an icon so groups are easy to spot on mobile.</p></div><button class="close" onclick="closeModal()">×</button></div><form id="groupForm" class="form-grid"><label class="field">Group name<input id="groupName" required placeholder="e.g. Japan Trip"></label><label class="field">Description<input id="groupDesc" placeholder="Optional"></label><div><strong style="font-size:13px">Group icon</strong><input type="hidden" id="groupIconInput" value="🍜"><div class="avatar-picker group-icon-picker">${GROUP_ICONS.map((a,i)=>`<button type="button" class="avatar-choice group-icon-choice ${i===0?'selected':''}" data-group-icon="${a}" onclick="selectGroupIcon(this,'${a}')">${a}</button>`).join('')}</div></div>${state.friends.length?`<div><strong style="font-size:13px">Add friends</strong><div class="checks" style="margin-top:8px">${state.friends.map(f=>`<label class="check"><input type="checkbox" name="friend" value="${f.id}">${avatar(f.display_name,f.avatar_key)}<span>${esc(f.display_name)}<small class="muted">${esc(f.email)}</small></span></label>`).join('')}</div></div>`:'<div class="notice">You have no friends yet. The group will start with just you; friends can be added later.</div>'}<button class="primary wide">Create group</button></form>`);
window.selectGroupIcon=(el,key)=>{const input=$('groupIconInput');if(input)input.value=key;document.querySelectorAll('.group-icon-choice').forEach(x=>x.classList.toggle('selected',x===el))};
document.addEventListener('submit',async e=>{if(e.target.id==='groupForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=friend]:checked')].map(x=>x.value);const icon=$('groupIconInput')?.value||GROUP_ICONS[0];const {data,error}=await sb.rpc('create_group_with_members',{group_name:$('groupName').value.trim(),group_description:$('groupDesc').value.trim(),member_ids:ids});if(error)toast(error.message);else{const iconResult=await sb.rpc('set_group_icon',{target_group_id:data,new_icon_key:icon});if(iconResult.error)toast(iconResult.error.message);closeModal();await loadGroups();toast('Group created');openGroup(data)}}});

window.openGroup=async id=>{
  const group=state.groups.find(g=>g.id===id)||{id,name:'Group'};state.activeGroup=group;
  const [{data:members,error:e1},{data:expenses,error:e2},{data:settlements,error:e3}]=await Promise.all([
    sb.from('group_members').select('user_id,profiles(id,display_name,email,avatar_key)').eq('group_id',id),
    sb.from('expenses').select('id,description,amount,currency,expense_date,paid_by,created_at,payer:profiles!expenses_paid_by_fkey(id,display_name,avatar_key),expense_splits(user_id,amount,profile:profiles(id,display_name,email,avatar_key))').eq('group_id',id).order('created_at',{ascending:false}),
    sb.from('settlements').select('id,from_user,to_user,amount,currency,created_at,recorded_by,from_profile:profiles!settlements_from_user_fkey(id,display_name),to_profile:profiles!settlements_to_user_fkey(id,display_name),recorder:profiles!settlements_recorded_by_fkey(id,display_name)').eq('group_id',id).order('created_at',{ascending:false})
  ]);if(e1)throw e1;if(e2)throw e2;if(e3)throw e3;state.members=(members||[]).map(m=>m.profiles);state.expenses=expenses||[];state.settlements=settlements||[];renderGroup();
}
function currenciesInGroup(){return [...new Set([...state.expenses.map(e=>e.currency||'IDR'),...state.settlements.map(s=>s.currency||'IDR')])].sort((a,b)=>a==='IDR'?-1:b==='IDR'?1:a.localeCompare(b))}
function calculateBalances(currency='IDR'){const b=Object.fromEntries(state.members.map(m=>[m.id,0]));for(const e of state.expenses.filter(x=>(x.currency||'IDR')===currency)){b[e.paid_by]=(b[e.paid_by]||0)+Number(e.amount);for(const sp of e.expense_splits)b[sp.user_id]=(b[sp.user_id]||0)-Number(sp.amount)}for(const st of state.settlements.filter(x=>(x.currency||'IDR')===currency)){b[st.from_user]=(b[st.from_user]||0)+Number(st.amount);b[st.to_user]=(b[st.to_user]||0)-Number(st.amount)}return b}
function allBalances(){return Object.fromEntries(currenciesInGroup().map(c=>[c,calculateBalances(c)]))}
function simplifyDebts(currency='IDR'){const b=calculateBalances(currency),credit=[],debt=[],out=[];Object.entries(b).forEach(([id,v])=>{if(v>0.005)credit.push({id,amount:v});if(v<-0.005)debt.push({id,amount:-v})});let i=0,j=0;while(i<debt.length&&j<credit.length){const x=Math.min(debt[i].amount,credit[j].amount);out.push({from:debt[i].id,to:credit[j].id,amount:x,currency});debt[i].amount-=x;credit[j].amount-=x;if(debt[i].amount<.005)i++;if(credit[j].amount<.005)j++}return out}
function memberName(id){return state.members.find(m=>m.id===id)?.display_name||'Unknown'}
function totalsByCurrency(rows){const m={};for(const r of rows){const c=r.currency||'IDR';m[c]=(m[c]||0)+Number(r.amount)}return m}
function settlementStats(){const sent={},received={},total={};for(const s of state.settlements){const c=s.currency||'IDR';total[c]=(total[c]||0)+Number(s.amount);if(s.from_user===state.user.id)sent[c]=(sent[c]||0)+Number(s.amount);if(s.to_user===state.user.id)received[c]=(received[c]||0)+Number(s.amount)}const net={};for(const c of new Set([...Object.keys(sent),...Object.keys(received)]))net[c]=(received[c]||0)-(sent[c]||0);return {sent,received,net,total}}
function settlementAction(x){if(x.from===state.user.id)return `<button class="small-btn settle-btn" onclick="recordSettlement('${x.from}','${x.to}',${x.amount},'${x.currency}')">I paid</button>`;if(x.to===state.user.id)return `<button class="small-btn settle-btn" onclick="recordSettlement('${x.from}','${x.to}',${x.amount},'${x.currency}')">Mark received</button>`;return ''}
function renderSettlementHistory(){if(!state.settlements.length)return '<div class="empty">No repayments recorded yet.</div>';return state.settlements.map(s=>{const mineOut=s.from_user===state.user.id,mineIn=s.to_user===state.user.id;let cash='Group transfer';let cls='';if(mineOut){cash='Cash out';cls='negative'}else if(mineIn){cash='Cash in';cls='positive'}const rec=s.recorder?.display_name?` · recorded by ${esc(s.recorder.display_name)}`:'';return `<div class="row settlement-row"><div class="currency-badge">${esc(s.currency||'IDR')}</div><div class="grow"><strong>${esc(s.from_profile.display_name)} → ${esc(s.to_profile.display_name)}</strong><span>${fmtDateTime(s.created_at)}${rec}</span></div><div class="amt"><strong class="${cls}">${mineIn?'+':mineOut?'-':''}${money(s.amount,s.currency||'IDR')}</strong><span>${cash}</span></div></div>`}).join('')}
function renderGroup(){
  document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('groupDetail').classList.remove('hidden');
  const closed=state.activeGroup.status==='closed',owner=state.activeGroup.created_by===state.user.id;
  $('pageTitle').innerHTML=`<span class="page-title-with-icon">${groupIcon(state.activeGroup,'title-group-icon')}<span>${esc(state.activeGroup.name)}</span></span>`;$('pageSub').textContent=closed?'Closed group · read-only':(state.activeGroup.description||`${state.members.length} members`);
  $('topActions').innerHTML=closed?`${owner?'<button class="danger-outline" onclick="confirmDeleteGroup()">Delete group</button>':''}`:`<button class="secondary" onclick="showAddMembers()">+ Member</button> <button class="secondary" onclick="showManualSettlement()">+ Settlement</button> <button class="primary" onclick="showAddExpense()">+ Expense</button> <button class="more-btn" onclick="showGroupSettings()" title="Group settings">•••</button>`;
  const currencies=currenciesInGroup();const balances=allBalances();const myBalance=Object.fromEntries(currencies.map(c=>[c,balances[c]?.[state.user.id]||0]));const spend=totalsByCurrency(state.expenses);const ss=settlementStats();const debts=currencies.flatMap(c=>simplifyDebts(c));
  const balanceCls=Object.values(myBalance).some(v=>v<-.005)?'negative':'positive';
  const settleHtml=debts.length?currencies.map(c=>{const rows=debts.filter(d=>d.currency===c);if(!rows.length)return '';return `<div class="settle-currency-group"><div class="settle-currency-title">${c}</div>${rows.map(x=>`<div class="row suggested">${memberAvatar(x.from)}<div class="grow"><strong>${esc(memberName(x.from))} → ${esc(memberName(x.to))}</strong><span>${x.from===state.user.id?'You owe this':x.to===state.user.id?'You should receive this':'Suggested settlement'}</span></div><div class="amt"><strong>${money(x.amount,c)}</strong></div>${closed?'':settlementAction(x)}</div>`).join('')}</div>`}).join(''):'<div class="empty success-empty"><div>✓</div>All settled!</div>';
  $('groupDetail').innerHTML=`<button class="back" onclick="renderGroups()">← All groups</button>${closed?'<div class="notice closed-notice" style="margin-top:16px"><strong>Group closed.</strong> History is preserved, but no new expenses, members, or settlements can be added.</div>':''}<div class="summary summary-four stagger" style="margin-top:16px"><div class="card metric"><span class="muted">Your balance</span>${moneyLines(myBalance)}<span class="muted">Net position by currency</span></div><div class="card metric"><span class="muted">Group spend</span>${moneyLines(spend)}<span class="muted">${state.expenses.length} expense${state.expenses.length===1?'':'s'}</span></div><div class="card metric"><span class="muted">Cash received</span>${moneyLines(ss.received,'positive')}<span class="muted">Settlement cash in</span></div><div class="card metric"><span class="muted">Cash paid</span>${moneyLines(ss.sent,'negative')}<span class="muted">Settlement cash out</span></div></div><div class="group-layout"><div class="panel lift"><div class="head"><div><h2>Expenses</h2><p>What created the balances</p></div>${closed?'':'<button class="ghost-link" onclick="showAddExpense()">Add expense</button>'}</div>${state.expenses.length?state.expenses.map(e=>`<div class="row"><div class="currency-badge">${esc(e.currency||'IDR')}</div><div class="grow"><strong>${esc(e.description)}</strong><span>${fmtDate(e.expense_date||e.created_at)} · paid by ${esc(e.payer.display_name)}</span></div><div class="amt"><strong>${money(e.amount,e.currency||'IDR')}</strong><span>${e.expense_splits.length} people</span></div></div>`).join(''):'<div class="empty">No expenses yet.</div>'}</div><div class="panel lift"><div class="head"><div><h2>Settle up</h2><p>Suggested transfers after netting</p></div></div>${settleHtml}</div></div><div class="panel lift settlement-panel"><div class="head"><div><h2>Settlement tracker</h2><p>Actual repayments — tracked by currency</p></div>${closed?'':'<button class="secondary" onclick="showManualSettlement()">+ Record settlement</button>'}</div><div class="cash-summary"><div><span>Cash in</span>${moneyLines(ss.received,'positive')}</div><div><span>Cash out</span>${moneyLines(ss.sent,'negative')}</div><div><span>Net cash</span>${moneyLines(ss.net,Object.values(ss.net).some(v=>v<-.005)?'negative':'positive')}</div><div><span>Group settlement volume</span>${moneyLines(ss.total)}</div></div><div class="history-list">${renderSettlementHistory()}</div></div>`
}

function renderSideAvatar(){const el=$('sideAvatar');if(!el)return;const key=state.profile?.avatar_key||'';el.textContent=AVATARS.includes(key)?key:initials(state.profile?.display_name);el.classList.toggle('emoji-avatar',AVATARS.includes(key))}
window.showAvatarPicker=()=>modal(`<div class="modalhead"><div><h2>Choose your icon</h2><p class="modal-sub">24 lightweight presets — no image upload or storage needed.</p></div><button class="close" onclick="closeModal()">×</button></div><div class="avatar-picker">${AVATARS.map(a=>`<button class="avatar-choice ${state.profile.avatar_key===a?'selected':''}" onclick="saveAvatar('${a}')">${a}</button>`).join('')}</div><button class="secondary wide" style="margin-top:14px" onclick="saveAvatar('')">Use initials</button>`);
window.saveAvatar=async key=>{const {data,error}=await sb.from('profiles').update({avatar_key:key||null}).eq('id',state.user.id).select().single();if(error)return toast(error.message);state.profile=data;renderSideAvatar();closeModal();toast('Icon updated');if(state.activeGroup)await openGroup(state.activeGroup.id);else renderDashboard()};

window.showGroupSettings=()=>{const owner=state.activeGroup.created_by===state.user.id;modal(`<div class="modalhead"><div><h2>Group settings</h2><p class="modal-sub">Change the group icon${owner?' or manage its lifecycle':''}.</p></div><button class="close" onclick="closeModal()">×</button></div><div class="settings-actions"><button class="secondary wide settings-icon-row" onclick="showGroupIconPicker()">${groupIcon(state.activeGroup,'settings-group-icon')}<span><strong>Change group icon</strong><small>Choose from 24 presets</small></span><b>›</b></button>${owner?'<button class="danger-outline wide" onclick="confirmCloseGroup()">Close group</button><p class="muted settings-help">Closing keeps all history, but makes the group read-only.</p><button class="danger wide" onclick="confirmDeleteGroup()">Delete group permanently</button><p class="muted settings-help">Deleting permanently removes the group, expenses, splits, and settlement history.</p>':''}</div>`)};
window.showGroupIconPicker=()=>modal(`<div class="modalhead"><div><h2>Choose group icon</h2><p class="modal-sub">Use a preset so it stays fast and storage-free.</p></div><button class="close" onclick="closeModal()">×</button></div><div class="avatar-picker group-icon-picker">${GROUP_ICONS.map(a=>`<button class="avatar-choice ${state.activeGroup.icon_key===a?'selected':''}" onclick="saveGroupIcon('${a}')">${a}</button>`).join('')}</div>`);
window.saveGroupIcon=async key=>{const {error}=await sb.rpc('set_group_icon',{target_group_id:state.activeGroup.id,new_icon_key:key});if(error)return toast(error.message);state.activeGroup.icon_key=key;await loadGroups();closeModal();renderGroup();toast('Group icon updated')};
window.confirmCloseGroup=()=>modal(`<div class="modalhead"><h2>Close group?</h2><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="notice">All history will remain visible, but nobody can add new expenses, members, or settlements.</div><button class="danger wide" onclick="closeCurrentGroup()">Yes, close group</button><button class="secondary wide" onclick="closeModal()">Cancel</button></div>`);
window.closeCurrentGroup=async()=>{const {error}=await sb.rpc('close_group',{target_group_id:state.activeGroup.id});if(error)return toast(error.message);closeModal();await loadGroups();await openGroup(state.activeGroup.id);toast('Group closed')};
window.confirmDeleteGroup=()=>modal(`<div class="modalhead"><h2>Delete group permanently?</h2><button class="close" onclick="closeModal()">×</button></div><form id="deleteGroupForm" class="form-grid"><div class="notice danger-notice">This cannot be undone. All expenses and settlement history in <strong>${esc(state.activeGroup.name)}</strong> will be deleted.</div><label class="field">Type DELETE to confirm<input id="deleteGroupConfirm" autocomplete="off" required placeholder="DELETE"></label><button class="danger wide">Delete permanently</button><button type="button" class="secondary wide" onclick="closeModal()">Cancel</button></form>`);
document.addEventListener('submit',async e=>{if(e.target.id==='deleteGroupForm'){e.preventDefault();if($('deleteGroupConfirm').value.trim()!=='DELETE')return toast('Type DELETE to confirm');const {error}=await sb.rpc('delete_group',{target_group_id:state.activeGroup.id});if(error)return toast(error.message);closeModal();state.activeGroup=null;await loadGroups();renderGroups();toast('Group deleted')}});

window.showAddMembers=()=>{const existing=new Set(state.members.map(m=>m.id)),eligible=state.friends.filter(f=>!existing.has(f.id));modal(`<div class="modalhead"><h2>Add group members</h2><button class="close" onclick="closeModal()">×</button></div>${eligible.length?`<form id="addMembersForm" class="form-grid"><div class="checks">${eligible.map(f=>`<label class="check"><input type="checkbox" name="member" value="${f.id}">${avatar(f.display_name,f.avatar_key)}<span>${esc(f.display_name)}<small class="muted">${esc(f.email)}</small></span></label>`).join('')}</div><button class="primary wide">Add selected</button></form>`:'<div class="empty">All of your friends are already in this group.</div>'}`)};
document.addEventListener('submit',async e=>{if(e.target.id==='addMembersForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=member]:checked')].map(x=>x.value);const {error}=await sb.rpc('add_group_members',{target_group_id:state.activeGroup.id,member_ids:ids});if(error)toast(error.message);else{closeModal();await openGroup(state.activeGroup.id);toast('Members added')}}});

window.showAddExpense=()=>{modal(`<div class="modalhead"><div><h2>Add expense</h2><p class="modal-sub">Record when it happened, who paid, and in what currency.</p></div><button class="close" onclick="closeModal()">×</button></div><form id="expenseForm" class="form-grid"><label class="field">Description<input id="expenseDesc" required placeholder="e.g. Dinner"></label><div class="form-row"><label class="field">Expense date<input id="expenseDate" type="date" value="${todayISO()}" required></label><div class="money-field"><span class="field-label">Amount</span><div class="money-input"><select id="expenseCurrency">${currencyOptions('IDR')}</select><input id="expenseAmount" type="text" inputmode="decimal" required placeholder="150000"></div><small class="amount-preview" id="expenseAmountPreview">${money(0,'IDR')}</small></div></div><label class="field">Paid by<select id="expensePayer">${state.members.map(m=>`<option value="${m.id}" ${m.id===state.user.id?'selected':''}>${esc(m.display_name)}</option>`).join('')}</select></label><div><strong style="font-size:13px">Split equally between</strong><div class="checks" style="margin-top:8px">${state.members.map(m=>`<label class="check"><input type="checkbox" name="split" value="${m.id}" checked>${avatar(m.display_name,m.avatar_key)}<span>${esc(m.display_name)}</span></label>`).join('')}</div></div><button class="primary wide">Save expense</button></form>`);bindMoneyField('expenseAmount','expenseCurrency','expenseAmountPreview')};
document.addEventListener('submit',async e=>{if(e.target.id==='expenseForm'){e.preventDefault();const ids=[...e.target.querySelectorAll('input[name=split]:checked')].map(x=>x.value),amount=parseMoneyInput($('expenseAmount').value),currency=$('expenseCurrency').value,date=$('expenseDate').value;if(!ids.length)return toast('Select at least one person');if(!amount||amount<=0)return toast('Enter a valid amount');const {error}=await sb.rpc('create_equal_expense_v2',{target_group_id:state.activeGroup.id,expense_description:$('expenseDesc').value.trim(),expense_amount:amount,expense_currency:currency,expense_happened_on:date,payer_id:$('expensePayer').value,participant_ids:ids});if(error)toast(error.message);else{closeModal();await openGroup(state.activeGroup.id);toast('Expense added')}}});

window.showManualSettlement=()=>{const others=state.members.filter(m=>m.id!==state.user.id);if(!others.length)return toast('Add another member first');modal(`<div class="modalhead"><div><h2>Record settlement</h2><p class="modal-sub">Record an actual money transfer in its original currency.</p></div><button class="close" onclick="closeModal()">×</button></div><form id="settlementForm" class="form-grid"><label class="field">What happened?<select id="settlementDirection"><option value="paid">I paid someone</option><option value="received">Someone paid me</option></select></label><label class="field" id="counterpartyLabel">Paid to<select id="settlementCounterparty">${others.map(m=>`<option value="${m.id}">${esc(m.display_name)}</option>`).join('')}</select></label><div class="money-field"><span class="field-label">Amount</span><div class="money-input"><select id="settlementCurrency">${currencyOptions('IDR')}</select><input id="settlementAmount" type="text" inputmode="decimal" required placeholder="150000"></div><small class="amount-preview" id="settlementAmountPreview">${money(0,'IDR')}</small></div><div class="notice soft">This affects balances as a repayment, not as a new expense.</div><button class="primary wide">Record settlement</button></form>`);$('settlementDirection').onchange=()=>{$('counterpartyLabel').childNodes[0].nodeValue=$('settlementDirection').value==='paid'?'Paid to':'Received from'};bindMoneyField('settlementAmount','settlementCurrency','settlementAmountPreview')};
document.addEventListener('submit',async e=>{if(e.target.id==='settlementForm'){e.preventDefault();const dir=$('settlementDirection').value,other=$('settlementCounterparty').value,amount=parseMoneyInput($('settlementAmount').value),currency=$('settlementCurrency').value;const from=dir==='paid'?state.user.id:other,to=dir==='paid'?other:state.user.id;await saveSettlement(from,to,amount,currency)}});

async function saveSettlement(from,to,amount,currency='IDR'){if(!amount||amount<=0)return toast('Enter a valid amount');const {error}=await sb.from('settlements').insert({group_id:state.activeGroup.id,from_user:from,to_user:to,amount:Math.round(amount*100)/100,currency,recorded_by:state.user.id});if(error)toast(error.message);else{closeModal();await openGroup(state.activeGroup.id);toast('Settlement recorded')}}
window.recordSettlement=async(from,to,amount,currency='IDR')=>{const action=from===state.user.id?'Confirm that you paid':'Confirm that you received';if(!confirm(`${action} ${money(amount,currency)}?`))return;await saveSettlement(from,to,amount,currency)};

document.addEventListener('pointerdown',e=>{const target=e.target.closest('button,.group-card');if(!target||target.disabled)return;target.classList.add('pressing');setTimeout(()=>target.classList.remove('pressing'),180)});
document.addEventListener('click',e=>{const target=e.target.closest('button,.group-card');if(!target||target.disabled)return;const r=target.getBoundingClientRect(),dot=document.createElement('span');dot.className='tap-ripple';const size=Math.max(r.width,r.height)*1.4;dot.style.width=dot.style.height=`${size}px`;dot.style.left=`${e.clientX-r.left-size/2}px`;dot.style.top=`${e.clientY-r.top-size/2}px`;target.classList.add('ripple-surface');target.appendChild(dot);setTimeout(()=>dot.remove(),520)});

init().catch(err=>{console.error(err);toast(err.message||'Something went wrong')});
